### ISSUE TITLE
setup error: UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 4006: illegal multibyte sequence

### ISSUE THREAD

**Issue by sander314** [rmarkello/peakdet#21]
Running setup causes an error.
```
(base) E:\peakdet>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    main()
  File "setup.py", line 19, in main
    ldict['LONG_DESCRIPTION'] = src.read()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 4006: illegal multibyte sequence

```

This is related to the issue described in https://github.com/gautamkrishnar/socli/issues/143 and can be fixed by replacing/removing all the extended ASCII characters (particularly ` ) in README.rst. 
Note, this is windows 7 set to Korean.

**Comment by rmarkello** [comment]
Hi @sander314 ! Welcome to `peakdet` and thanks for the bug report :bug:

 I'm not sure if it was the ` character or if it was the emoji (:sparkles:), so for now, I've made a PR (#22) to get rid of the latter and update the setup.py to ensure utf-8 encoding is used when opening the README.rst.

Once the tests are a go I'll merge it in and if you want to give it another shot that would be awesome!

**Comment by sander314** [comment]
Can confirm that adding encoding='utf-8' fixes the issue, even if you keep the sparkles and ` in the readme.

**Comment by rmarkello** [comment]
Great! Thanks so much for confirming.
